#!/usr/bin/env python

import sys

from rqt_drone_teleop.drone_teleop import DroneTeleop
from rqt_gui.main import Main

plugin = 'rqt_drone_teleop'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
