#!/usr/bin/env python

import sys

from rqt_pos_teleop.pos_teleop import PosTeleop
from rqt_gui.main import Main

plugin = 'rqt_pos_teleop'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
