#!/usr/bin/env python

import sys

from rqt_vel_teleop.vel_teleop import VelTeleop
from rqt_gui.main import Main

plugin = 'rqt_vel_teleop'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
