#!/usr/bin/env python

import sys

from rqt_ground_robot_teleop.ground_robot_teleop import GroundRobotTeleop
from rqt_gui.main import Main

plugin = 'rqt_ground_robot_teleop'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
