#!/usr/bin/env python

import sys

from rqt_follow_road.follow_road import FollowRoad
from rqt_gui.main import Main

plugin = 'rqt_follow_road'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
